[[channels]]
name = "ssh-hosts"
command = """grep -i -E '^[[:space:]]*Host[[:space:]]' ~/.ssh/config 2>/dev/null | awk '{for (i=2; i<=NF; i++) print $i}' | grep -v '*'"""
preview = """grep -i -A 5 -E "^[[:space:]]*Host {}$" ~/.ssh/config"""
